### ISSUE TITLE
ws are not calling with described process

### ISSUE THREAD

**Issue by sbihan** [xtivia/dxp-rest-example#1]
Hello, 

I've deployed on a Liferay DXP your dxp-rest-example jar. On starting, i saw some logs : 

The sample DXP REST app has been activated/updated at Fri Sep 02 14:20:16 GMT 2016
For sample DXP REST config, info=unknown
For sample DXP REST config, infoNum=5

Then i've configured path /rest on back office to reach WS but when i try to call, for example, this one : 
http://localhost:8080/o/rest/samples/users/current  

-> I have a 404 :

14:16:06,279 WARN  [http-nio-8080-exec-5][code_jsp:181] {code="404", msg="ProxyServlet: /rest/samples/users/current", uri=/o/rest/samples/users/current}

Do you any idea of what i've missed ? 

Thanks !

Sébastien

**Comment by mfreeman-xtivia** [comment]
Sebastien

Can you please confirm that you se
t the configuration for BOTH the CXF configuration and the REST configuration to /rest in the Control Panel? It appears to me at first glance that Liferay DXP cannot resolve the route to the JAX-RS services

Search for CXF Endpoints
Create new CXFEndpoint publisher configuration providing value for Context Path (/rest)
Go back to System Settings > Foundation and select REST Extender
Create new Rest Extender configuration (search with rest) providing Context Path (/rest)

**Comment by sbihan** [comment]
Hello, 

You are right. I've made a mistake in back office configuration. It's work now. Thanks for your answer and your sample. 

Sébastien
